---
singleServerConfig:
   idleConnectionTimeout: 10000
   pingTimeout: 1000
   connectTimeout: 10000
   timeout: 3000
   retryAttempts: 3
   retryInterval: 1500
   reconnectionTimeout: 3000
   subscriptionsPerConnection: 5
   clientName: null
   address: "redis://localhost:6379"
   subscriptionConnectionMinimumIdleSize: 1
   subscriptionConnectionPoolSize: 50
   connectionMinimumIdleSize: 10
   connectionPoolSize: 64
threads: 0
nettyThreads: 0
codec: !<org.redisson.client.codec.StringCodec> {}